### ISSUE TITLE
feature transformer initialization uses wrong distribution

### ISSUE THREAD

**Issue by Sopel97** [glinscott/nnue-pytorch#113]
FT weight and bias distribution is normal (randn) instead of uniform (rand)

**Comment by vondele** [comment]
do we have a test that shows one of the other distributions is better or worse?

**Comment by Sopel97** [comment]
They are probably about equivalent because it wasn't catched with #96

**Comment by vondele** [comment]
well that merge had an issue, (related to the transpose and ranger), and one always assumes just a single issue. So maybe worthwhile checking carefully nevertheless.

**Comment by Sopel97** [comment]
can't find it anymore, not sure what changed. closing
