### ISSUE TITLE
Remove the python data loader?

### ISSUE THREAD

**Issue by Sopel97** [glinscott/nnue-pytorch#116]
Maybe we should consider removing the python data loader? It's not usable in practical terms, and drags behind the need of updating it along the c++ data loader.

**Comment by glinscott** [comment]
The one reason I had left it around was for using the built-in pytorch quantization utilities, as they don't get along well with Sparse Tensors (of course).  Agreed that updating it is a pain though, maybe shuffle it off to an experimental directory, along with things like qmodel.py?

**Comment by vondele** [comment]
I think gary's suggestion is a good one.

**Comment by Sopel97** [comment]
perhaps better to keep these only in the version control, create an "issue" that links to them, and saying that stuff needs to be done around it. Keeping stuff that doesn't work, or is unused, in master is not needed imo when we have full history.

**Comment by vondele** [comment]
I was thinking an experimental branch, not master + directory. But yes, we have fully history. Question is how to find it back. Using an issue with docs is probably an alternative, either works for me. Having the master clean and concise is an advantage.
