### ISSUE TITLE
Where to find training data?

### ISSUE THREAD

**Issue by adalsteinnpals** [glinscott/nnue-pytorch#159]
This is not really an issue, but still information that I have yet to find.
Where can I find suggestions on training data (train_data.bin val_data.bin) to train the model?

All the best,

**Comment by vondele** [comment]
This is rather well documented on the wiki:
https://github.com/glinscott/nnue-pytorch/wiki/Training-datasets

Let us know how it goes... training for SF is also actively discussed on our discord.

**Comment by adalsteinnpals** [comment]
Thank you for the swift reply vondele
