### ISSUE TITLE
Problem when trying to run train.py

### ISSUE THREAD

**Issue by Sopel97** [glinscott/nnue-pytorch#16]
When I try to run current train.py with `python train.py 10m_d3_2.binpack d8_100000.binpack --num-workers=3 --threads=1 --batch-size=512` I get the following stack trace:
```
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    main()
  File "train.py", line 68, in main
    checkpoint_callback = pl.callbacks.ModelCheckpoint(save_last=True)
  File "C:\Programy\Python36\lib\site-packages\pytorch_lightning\callbacks\model
_checkpoint.py", line 173, in __init__
    self.__validate_init_configuration()
  File "C:\Programy\Python36\lib\site-packages\pytorch_lightning\callbacks\model
_checkpoint.py", line 251, in __validate_init_configuration
    'ModelCheckpoint(save_last=True, monitor=None) is not a valid configuration.
'
pytorch_lightning.utilities.exceptions.MisconfigurationException: ModelCheckpoin
t(save_last=True, monitor=None) is not a valid configuration. You can save the l
ast checkpoint with ModelCheckpoint(save_top_k=None, monitor=None)
```

**Comment by vondele** [comment]
Copying from discord:
interesting .. it is a warning here.
(it also does work, i.e. writes the last checkout and every checkpoint with improved validation score, storing only one of those)
`distributed.py:45: UserWarning: ModelCheckpoint(save_last=True, monitor=None) is a redundant configuration. You can save the last checkpoint with ModelCheckpoint(save_top_k=None, monitor=None).`

**Comment by glinscott** [comment]
This is fixed by using a newer version of pytorch lightning (`pip install --upgrade pytorch-lightning`).
