### ISSUE TITLE
How to make the trainer work on CPU only mode now?

### ISSUE THREAD

**Issue by PikaCat-OuO** [glinscott/nnue-pytorch#198]
I found out that glinscott/nnue-pytorch#87 managed to run the trainer on cpu only mode.
But as I notice that at some point glinscott/nnue-pytorch@0764091 a custom kernel has been applied to the feature transformer.
So It means more changes need to be applied to make it work on cpu side.

May I ask what should I do to the rawKernel code and other stuff to make it work on cpu?

**Comment by Sopel97** [comment]
The main reason the custom kernels were created is that some specific pytorch's tensors and operations are too slow for our needs. This includes both CPU and GPU code. So I don't think it's possible to get a good solution without duplicating the work that went into writing the CUDA kernels and writing an optimized implementation in C++ that works on pytorch tensors. 

The classes that encapsulate the current kernels and provide seemless interoperation with pytorch would then have to dispatch into either CUDA kernels or C++ code, based on the location of the inputs.

Additional work is required to make cupy an optional dependency, as right now it's imported eagerly, even though kernels are compiled lazily.
