### ISSUE TITLE
error on startup: Trainer.root_gpu was deprecated

### ISSUE THREAD

**Issue by jdart1** [glinscott/nnue-pytorch#212]
I have followed the setup steps in the README, and installed CuPy version 11.7. I am getting this error on startup:
```

Traceback (most recent call last):
File "train.py", line 154, in <module>
    main()
  File "train.py", line 129, in main
    main_device = trainer.root_device if trainer.root_gpu is None else 'cuda:' + str(trainer.root_gpu)
File "/home/jdart/.local/lib/python3.8/site-packages/pytorch_lightning/_graveyard/trainer.py", line 53, in _root_gpu
    raise AttributeError(
AttributeError: `Trainer.root_gpu` was deprecated in v1.6 and is no longer accessible as of v1.8. Please use `Trainer.strategy.root_device.index` instead.
```

System is Ubuntu 20.04

**Comment by Sopel97** [comment]
The trainer was initially written for pytorch 1.7 I believe, and there have been some changes since. This will be looked at, for now I suggest to downgrade to pytorch 1.7

**Comment by linrock** [comment]
The crash happens when newer pytorch-lightning versions are used (see linked PR for the fix)

You can work around it in the meantime with an older version less than 1.8, where `Trainer.root_gpu` was removed:

`pip install pytorch-lightning==1.7.7`

**Comment by ThatGuyCalledJesse** [comment]
I have this issue too, and I'm using 1.7.7
