### ISSUE TITLE
Cannot find data_loader shared library

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [glinscott/nnue-pytorch#218]
I made a python env, installed all packages, generated the training data (and val data). But when I run
``python3 train.py train_data.bin val_data.bin --gpus 1``
I get the error
``Cannot find data_loader shared library``

**Comment by Sopel97** [comment]
Have you compiled the data loader? https://github.com/glinscott/nnue-pytorch#build-the-fast-dataloader

**Comment by ThatGuyCalledJesse** [comment]
I am so sorry, I reinstalled it because a new PC, and I forgot to compile it
