### ISSUE TITLE
Creating a new .binpack or .bin dataset without generating it with Stockfish

### ISSUE THREAD

**Issue by benliu961** [glinscott/nnue-pytorch#232]
I have a dataset that was generated completely independently already but am unsure how to format it so that it is compatible with train.py. The dataset contains each fen and a corresponding value. How would I go about this? I can't seem to find any documentation about the actual format of the dataset besides them being either .bin or .binpack files. Any help is appreciated! Thank you!

**Comment by vondele** [comment]
you want to format your data in the .plain format, which can be converted .binpack with the tools branch. Docs here https://github.com/official-stockfish/Stockfish/blob/tools/docs/convert.md 
Not sure where the format is specified for .plain, but converting some binpack makes it quite clear:
```
fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
move e2e4
score 54
ply 0
result 1
e
fen rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
move e7e5
score -32
ply 1
result -1
e
fen rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2
move d2d4
score 45
ply 2
result 1
e
```

**Comment by benliu961** [comment]
Is this the .plain result from converting a .binpack to .plain?

**Comment by vondele** [comment]
yes.

**Comment by benliu961** [comment]
Sorry for the questions but if it is not too much work, could you explain the lines that aren't the fen?

**Comment by vondele** [comment]
move is the bestmove for that position
score is the score for that position
ply is the game ply
result is the outcome of the game this fen is part of.

**Comment by benliu961** [comment]
thank you very much!

**Comment by evanrussek** [comment]
Thank you for guidance on this! 

If I could ask a naive question --

Based on https://github.com/glinscott/nnue-pytorch/blob/master/docs/nnue.md, I understood the nnue model to just predict a single scalar value (centipawn) from board states.

Thus, what is the purpose of the move, ply and result inputs? Is this just to assist with formatting the input?

**Comment by vondele** [comment]
in the basic mode, just the board is used to predict the score. The move can be used to restrict which positions are used for training, for example, for SF we skip positions where the move is a capture, giving better results. Similarly we skip over positions with a small game ply.  As said, we can introduce part of the result in the fitting, i.e. we fit a combination of score and result. See https://github.com/glinscott/nnue-pytorch/blob/fc1547dabcde9883cf151e5891fd12af8685661c/model.py#L294-L315

**Comment by evanrussek** [comment]
Great. Thank you!
