### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by benliu961** [glinscott/nnue-pytorch#238]
Hello,

When I try to run train.py with my dataset, I eventually get an output of "Illegal instruction" after it prints "Using c++ data loader"

I have never run into this issue before and am unsure what approach I should take to fix it. What could be the cause of this problem and how should I resolve it?

Thank you

**Comment by Sopel97** [comment]
what's your CPU

**Comment by benliu961** [comment]
I had solved it, I didn't compile the data loader correctly.
