### ISSUE TITLE
Is it possible to convert a NNUE file (weights and biases) to emulate an older version?

### ISSUE THREAD

**Issue by SlowChess** [glinscott/nnue-pytorch#244]
For example : 

Is it possible to convert `nn-e8321e467bf6.nnue` file to emulate `nn-8a08400ed089.nnue` file?

-------------------------------
![image](https://github.com/glinscott/nnue-pytorch/assets/132969765/1e9cb5fa-c900-4ef7-8830-51edcac6d617)

-------------------------------

![image](https://github.com/glinscott/nnue-pytorch/assets/132969765/b0b38f0b-899d-41c5-bdac-92a4803f8f37)

-------------------------------

**Comment by vondele** [comment]
not that I know.

**Comment by penguingim1** [comment]
Thanks. I close this issue now but... If there's a tiny little chance that it makes possible...

**Comment by ginkgo20** [comment]
I reopen this issue because I couldn't find any way for do that.

**Comment by SlowChess** [comment]
- I close this issue due to https://github.com/official-stockfish/Stockfish/pull/4617

When NNUE file size reduce then we don't need to convert NNUE file to older version , Thanks @MaximMolchanov
