### ISSUE TITLE
"RuntimeError: shape '[41728, 256]' is invalid for input of size 10510996" when converting SF network

### ISSUE THREAD

**Issue by vshcherbyna** [glinscott/nnue-pytorch#38]
Hello,

Following example from the main page I am converting the last strongest SF net into the model using the command:

```
python serialize.py nn-62ef826d1a6d.nnue nn-62ef826d1a6d.pt
```

and it is failing with:

```
(env) C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch>python serialize.py nn-62ef826d1a6d.nnue nn-62ef826d1a6d.pt
Converting nn-62ef826d1a6d.nnue to nn-62ef826d1a6d.pt
Traceback (most recent call last):
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\serialize.py", line 187, in <module>
    main()
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\serialize.py", line 181, in main
    reader = NNUEReader(f, feature_set)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\serialize.py", line 112, in __init__
    self.read_feature_transformer(self.model.input)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\serialize.py", line 133, in read_feature_transformer
    weights = self.tensor(numpy.int16, layer.weight.shape[::-1])
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\serialize.py", line 127, in tensor
    d = d.reshape(shape)
RuntimeError: shape '[41728, 256]' is invalid for input of size 10510996
```

Any clues on the error?
Thank you,
With best regards,
Volodymyr

**Comment by vondele** [comment]
I think should work with `--features=HalfKP`

**Comment by vshcherbyna** [comment]
Thanks, adding --features=HalfKP made it work.

**Comment by Sopel97** [comment]
you need to implement https://github.com/glinscott/nnue-pytorch/blob/a13b4308e2c7abf21eca9cd829159cc7588a487e/halfkp.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L66 and https://github.com/glinscott/nnue-pytorch/blob/a13b4308e2c7abf21eca9cd829159cc7588a487e/halfkp.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L32. To make it work it would be enough to return an array of zeros, but it may be better for the trainer if reasonable values are provided like here https://github.com/glinscott/nnue-pytorch/blob/a13b4308e2c7abf21eca9cd829159cc7588a487e/halfka.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L70
