### ISSUE TITLE
training data format

### ISSUE THREAD

**Issue by lucasart** [glinscott/nnue-pytorch#79]
where can I find documentation for the binary format of training data ? my understanding is that it's just a bunch of (FEN, Result, Eval?) records, but binary compressed in some way (that I have yet to understand).

I would like to change c-chess-cli's export format to produce it directly:
https://github.com/lucasart/c-chess-cli#sampling

**Comment by lucasart** [comment]
answering my own question: [documentation here](https://github.com/glinscott/nnue-pytorch/blob/master/lib/nnue_training_data_formats.h)

sorry for the stupid question. closing.

**Comment by Sopel97** [comment]
I see you implemented the .bin format already. If you even want to tackle .binpack here's more info https://github.com/nodchip/Stockfish/blob/master/docs/binpack.md.

**Comment by lucasart** [comment]
I don't understand the purpose of binpack format, actually. If you just store all positions sequentially, indeed, you can do some compression trick there. But, don't you want to *sparsely* sample real games to produce the data, rather than take all positions that occur during games? This seems to be done ex-post in this repo. But, I think it's easier to do it ex-ante, and sample with the required frequency to produce a smaller `.bin` file. That way, you can remove some unnecessary logic on both side (producer -> no binpack stuff needed, consumer -> no sampling needed in training scripts).

For now, I just have a constant (user defined) sampling frequency. Perhaps something like `freq*exp(-lambda*ply)` would be better?

**Comment by Sopel97** [comment]
> But, don't you want to sparsely sample real games to produce the data

If someone shows that this helps training we could consider it, but as far as I know it has no visible impact. So we take 20x file size reduction instead.

**Comment by glinscott** [comment]
> I don't understand the purpose of binpack format, actually. If you just store all positions sequentially, indeed, you can do some compression trick there. But, don't you want to _sparsely_ sample real games to produce the data, rather than take all positions that occur during games? This seems to be done ex-post in this repo. But, I think it's easier to do it ex-ante, and sample with the required frequency to produce a smaller `.bin` file. That way, you can remove some unnecessary logic on both side (producer -> no binpack stuff needed, consumer -> no sampling needed in training scripts).

When training, we do many passes through the dataset, and the sampling skips different positions on each pass through.  So we end up seeing all positions in the dataset over a training run.  So binpack compression is a big win in terms of data size, since we do want all these positions.
